### ISSUE TITLE
use tagName instead of annotated tag

### ISSUE THREAD

**Issue by sharppanda** [saintedlama/versionize#15]
What is the reason of using annotation tag message instead of tag name.
Could we do:
`return repository.Tags.SingleOrDefault(t => t.FriendlyName == $"v{version}");`
instead of:
`return repository.Tags.SingleOrDefault(t => t.IsAnnotated && t.Annotation.Name == $"v{version}");`

**Comment by saintedlama** [comment]
Is it related to some issue you're facing? Could you provide an example where this decision results in a problem?

**Comment by saintedlama** [comment]
This could be related to https://github.com/saintedlama/versionize/issues/1

**Comment by saintedlama** [comment]
Fixed in version 1.6.1 released to nuget.org

**Comment by sharppanda** [comment]
I use mostly lightweight tags, therefore the discovery didn't work when I created a lightweight tag version manually.

**Comment by sharppanda** [comment]
Thank you for this super fast response.
