### ISSUE TITLE
feature request: option to stop before final commit and tag

### ISSUE THREAD

**Issue by achandlerwhite** [saintedlama/versionize#2]
I'd like to modify the changelog and some other project files before it is committed and the version tagged.

**Comment by achandlerwhite** [comment]
Yes that would be nice, and I assume that would also skip tagging right?

**Comment by saintedlama** [comment]
Implemented in version 1.2.0 https://www.nuget.org/packages/Versionize/1.2.0

**Comment by achandlerwhite** [comment]
Thanks!
