### ISSUE TITLE
Versioning of *.csproj

### ISSUE THREAD

**Issue by msallin** [saintedlama/versionize#6]
Hi

I would like to adjust versionize to work for the workflow I use, before I send a Pull Request I want to discuss my suggestion. there is a "Directory.Build.props" file in the root directory. It contains the attributes `VersionPrefix` and `VersionSuffix`. I expect versionize to pick to increment the `VersionPrefix`.

Example of a the file:
```
﻿<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix>rc1</VersionSuffix>
    <Authors />
    <Product>Xy</Product>
    <RepositoryUrl />
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```
My suggestion is simply to extend the `Discover`-method of `Projects.cs` to scan also for *.props. Furthermore, `Project.cs` has to be adjusted to pick and write to `VersionPrefix`, if it is present. Else use `Version` like it does now.
These changes make also other scenarios possible where one uses `Version` in the .props file or also using `VersionPrefix` int .csproj files.

Let me know what you think.

Marc

**Comment by saintedlama** [comment]
Is the use case that you want to release prerelease version such as rc1? The props file solution looks quite like a special use case to me.

**Comment by msallin** [comment]
Yes, this is the use case.

Well, I would not consider it as a special use case. The props file is the way for defining shared values in the new project-system. IMHO quite common among the folk who uses .NET Core.

**Comment by saintedlama** [comment]
I've a pre release functionality on my roadmap that should work somehow like this:
* If the --pre-release switch was set the version increment would be calculated and a for example -rc1 is appended
* In case the last version is a pre release the pre release version is incremented

Would that work for you?

The props files are standard but I want to avoid pulling to much msbuild functionality in the project.

**Comment by msallin** [comment]
Thanks for your answer. Unfortunatly, this isn't a possibility for us. Hence, I forked the project and will adjust it for our needs. Anyway, thank you for your work, I appreciate it!

**Comment by saintedlama** [comment]
Still interested in a PR in case the solution fits for more use cases. Ping me if you'd like to merge it back here
