### ISSUE TITLE
Version being bumped repeatedly without changes

### ISSUE THREAD

**Issue by AlexGoris-KasparSolutions** [saintedlama/versionize#7]
When running `versionize` repeatedly without any commits being added in between (aside from the ones versionize creates with each release), it keeps bumping the version number and generating new commits, tags, etc...

I would like to see Verzionize recognizing this situation and refusing to bump the version in such a case.
Any thoughts about this?

I would be willing to make a PR for this if the author likes the idea.

**Comment by saintedlama** [comment]
I like the idea :) I guess having a command line flag to trigger enable that behavior would be best for compatibility. In some workflows it makes sense to create a new version even if no change occured.
